package security.trust.concrete;

import org.jivesoftware.smack.util.Base64;
import org.whispersystems.libaxolotl.IdentityKey;
import security.trust.IIdentityWitness;

/**
 * Created by ben on 08/12/15.
 *
 * Concrete IIdentityWitness that authenticates a fingerprint.
 * If the fingerprint of the public key is identical to the one
 * generated by the input session public identity key than the
 * session identity key is authenticated
 *
 */
public class FingerprintWitness implements IIdentityWitness {
    private String fingerprint;
    public FingerprintWitness(String fingerprint)
    {
        this.fingerprint = fingerprint;
    }

    /**
     * Compares fingerprints with the identity key supplied
     * @param sessionIdentityKey identity key to compare FG with
     * @return
     */
    @Override
    public boolean authenticate(IdentityKey sessionIdentityKey) {
        return fingerprint.equals(sessionIdentityKey.getFingerprint().substring(3));
    }

    /**
     * Makes a displayable form of the witness witness
     * @return
     */
    @Override
    public String toString() {
        return fingerprint;
    }
}
