package Security;

import org.whispersystems.libaxolotl.IdentityKey;

/**
 * Created by ben on 08/12/15.
 *
 * Concrete IIdentityWitness that authenticates a fingerprint.
 * If the fingerprint of the public key is identical to the one
 * generated by the input session public identity key than the
 * session identity key is authenticated
 *
 */
public class FingerprintWitness implements IIdentityWitness {
    private String fingerprint;
    public FingerprintWitness(String fingerprint)
    {
        this.fingerprint = fingerprint;
    }

    @Override
    public boolean authenticate(IdentityKey sessionIdentityKey) {
        return fingerprint.equals(sessionIdentityKey.getFingerprint());
    }
}
